name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: |
        docker login -u rudycazabon -p 7394f3a3-29e3-4af7-8942-26820dfe32bf
    - name: Build the Docker Image
      run: |
        docker build . --file Dockerfile --tag ospstudio-docker:latest
    - name: Docker Push
      run: |
        docker push ospstudio-docker:latest
