name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker Image
      run: |
        docker build . --file Dockerfile --tag rjc/ubuntu:$(date +%s)
    - name: Docker Push
      run: |
        docker push ${{secrets.DOCKER_USER}}/ospstudio-docker
